name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        bun-version: [latest]
    
    defaults:
      run:
        working-directory: epitrello
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Bun ${{ matrix.bun-version }}
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: ${{ matrix.bun-version }}
    
    - name: Install dependencies
      run: bun i
    
    # - name: Run linter
    #   run: bun run lint
    #   continue-on-error: true
    
    - name: Run tests
      run: bun test
    
    - name: Build project with Vite
      run: bun run build
